name: Example pynt yml 
on: 
  workflow_dispatch:
    inputs: 
      comment: 
        type: string 
        default: "API Security tests"

env:
  PYNT_CREDENTIALS: "eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.lYk4El4szfu3n7nGSRANr0ZGxyR0Oa05It3Ww4rxamz5tjH7TnzOe-MLTuBfAEI6Vwhhf32ztikvuchJdpQ5oWWprRl5iL88m9Vd0MajvuRwZnVKlAXTfAeP5o5hZ338boyUTi-ZCdymxCagKDVRRyeQaJrgEMO0ScjHaw3IF3fyaTdT3LlvIFolNRty0c_GjPDLBczkKNyB8aq4qE4d9k5-nVY374A7Lo2d0z_1tqjSNuH_0fmN8kHXfnBmQ_4VdewVQQPs754RrFviWjuLd0aulHVlRe8beeLt1FaPCwC-V9Vw615Sssa7ahMCj05UfAtSwvjjY7SdBnUMk-zApA.akJm1LMGzZRA_woD.R3OC0Voe_-ioMrBGRxA8FobIGRIMH0sSX_z03gdH-Td0boVxGsNJEYWSXlEoVWLfUIhXak9fBwIwi3RDoNk2jZYuqdQLnnDpnpdObEmKRg61QJc0_qI-G4KklRdIk4EMyfc2AcxVCT0KZIDnn0SEiyvSBR4AobsB3SJGSf0WVvmaP_ekaqB1I_1OV-BkkjoUvH9AhgAC5bgAzPyarQ8I9T7hhInb4BxmlPeNaSK6RZh98NT0NpzD3ogQXlCPJnyd70WHwIAJ0D0JveEqjvLQ8EvVe4TKyGGLd2qIx_OyJQKoMdDeFa0ZZoQUQLSUi2BczSVuI6DGuax0Ah1RFvqOn0hVHKsDL62eDeX-HTdmfVcjBVPduHYvDaO2ANzNLzy4KNVXgIOrj4w5VPFFfPZkxcLVl60JozANhv1nNYiMyQ-dhdFVZl79oAW3nbg3PRGPMei0KKaNY0jmiWC6XZaDCk2WOykLjhy_xV9GzxpC7t8bDjbDxvP2t9JE8Nwgq2pIROpI1BaiW8Sjl3hWvNlhGqDWEJie77xSD9lNWWgP_BTKa95HhXwNfmmOXgzLkRH5rcybpkz-DYVRoONeX0yPDBLnDJ3m9P_Ji3W3W7WuoeqOXK15Os5WDVtb1GVrVeZ85yejj0WvCXZBhi2hUoCYX2zUr4LFkQ4qz-8VR-dcgHmYwCBJSdgncY63g8jMtGUAibl-bHnn0F7u86MUBgijfu_ryMGqg-lBWT_hDurhsOiwEymlfHfcazwO-Lxfqwrvp8xTkqi6iLF34EyAdG_-3V5xzJk5BWzu0D7SA1gj5ljjVYe-KJe1eI2v2XvPOGV3Iet3wMmm2QPG-_-5FUwJtAA-vmtOtitAU0UNFSn_5cM64uODl6mwEVMs93D26mAutxaCJ8RP--bR7Nu2bNDR4WMqzN0LR-gfXXcDzkAxOx6inSRRYmR9r7oL8ShcMGzj6si3Xc9LPKE2LwPXQgixweOXw1_VQF8_e4KSbTXOq78eIwEGswWj505puxOUzFNdk_JzLtAlA6H4L1jzNWc2HXx_NqksbWByi7cdQ0c7PJCWg98cmcW-5N-2S9CPDz-xoxSpPmOhSP4KzrX9qnRL-omRJ6KXY6ful5lMv7a0M2nPXwtcsmH3d6RZqdGVOeT5ynOzt3D3DUgpPuEz-6XMxTM6b5nUYsrzNG__QcemcTvPJJcV9wbg_ebx4UfXW9NeHw1o9xjKoCt02dOeioUlvettbquj3Ku44hyyKrtSZKsFo-Gbgg.s2ydihoUChm_sIvRh676Jw"

jobs:
 api-security:
  runs-on: ubuntu-latest

  steps: 
    - name: install pynt cli
      run: | 
        python3 -m pip install --upgrade pyntcli
        pip install websocket
    - name: get goat collection 
      run: | 
        curl https://raw.githubusercontent.com/pynt-io/pynt/main/goat_functional_tests/goat.postman_collection.json -o goat.json 
    - name: run pynt with newman integration 
      run: | 
        pynt newman --collection goat.json --reporters --return-error=errors-only
